-- Eigen namen voor de gescrapete recepten.
--
-- De bereiding was bij het importeren al herschreven, maar de titels stonden er
-- nog letterlijk zo in als bij de bron (Miljuschka, Uit Paulines Keuken, Jamie
-- Oliver, delicious.). Elk recept in de gedeelde pool krijgt hier een eigen
-- naam: zelfde gerecht, andere woorden, en zonder namen van makers of merken.
--
-- `titel` en `titel_nl` gaan allebei om, zodat de oorspronkelijke titel nergens
-- meer in de tabel staat. Die blijft alleen in data/recepten.json bewaard, als
-- `titel_bron`.
--
-- Op url, zoals 20260928000000: die is uniek, een titel niet. De oude naam
-- staat erbij als controle — is een titel intussen met de hand aangepast, dan
-- blijft die staan. Daardoor is opnieuw draaien ook onschuldig.
--
-- 439 recepten: de 438 uit data/recepten.json plus de minestrone uit
-- 20260929180000. De Hollandse klassiekers uit die migratie zijn eigen
-- recepten en blijven zoals ze zijn.

update recepten r
set titel = n.nieuw,
    titel_nl = n.nieuw
from (values
  ('https://www.jamieoliver.com/recipes/chicken/chicken-katsu-curry/', 'Kip katsu curry', 'Katsu-curry met krokante kip'),
  ('https://www.jamieoliver.com/recipes/pasta/veggie-pasta-bake/', 'Vegetarische pasta-ovenschotel', 'Pastaschotel met groenten uit de oven'),
  ('https://www.jamieoliver.com/recipes/chicken/garlic-chicken/', 'Knoflookkip', 'Kip met knoflook, kikkererwten en spinazie'),
  ('https://www.jamieoliver.com/recipes/chicken/cajun-chicken-traybake/', 'Cajun-kip uit de oven', 'Cajunkip van de bakplaat'),
  ('https://www.jamieoliver.com/recipes/beef/loaded-beefburger/', 'Gevulde runderburger', 'Runderburger met linzen en cheddar'),
  ('https://www.jamieoliver.com/recipes/lamb/lovely-lamb-balti/', 'Heerlijke lamsbalti', 'Lamsbalti'),
  ('https://www.jamieoliver.com/recipes/pasta/one-pan-veggie-lasagne/', 'Vegetarische lasagne uit één pan', 'Groentelasagne uit één pan'),
  ('https://www.jamieoliver.com/recipes/fish/air-fryer-salmon-with-crispy-potatoes/', 'Zalm uit de airfryer met krokante aardappeltjes', 'Airfryer-zalm met knapperige aardappeltjes'),
  ('https://www.jamieoliver.com/recipes/pasta/sweet-pea-orecchiette/', 'Orecchiette met zoete doperwten', 'Orecchiette met doperwten'),
  ('https://www.jamieoliver.com/recipes/rice/magic-baked-chicken-fried-rice/', 'Magische gebakken rijst met kip uit de oven', 'Gebakken rijst met kip uit de oven'),
  ('https://www.jamieoliver.com/recipes/vegetables/spinach-feta-and-lemon-filo-pie/', 'Filotaart met spinazie, feta en citroen', 'Filodeegtaart met spinazie, feta en citroen'),
  ('https://www.jamieoliver.com/recipes/fish/fantastic-fish-skewers/', 'Fantastische visspiesen', 'Visspiesen'),
  ('https://miljuschka.nl/pasta-recept-in-15-minuten-pasta-met-citroen/', 'Pasta met citroen', 'Citroenpasta in 15 minuten'),
  ('https://miljuschka.nl/ajam-smoor-indische-ketjap-kip/', 'Ajam smoor - Indische ketjap kip', 'Indische smoorkip in ketjapsaus'),
  ('https://miljuschka.nl/pasta-met-spinazie-en-bacon-eenpansgerecht/', 'Pasta met spinazie en bacon - eenpansgerecht', 'Eenpanspasta met spinazie en bacon'),
  ('https://miljuschka.nl/kipstoof-een-winterse-maaltijd/', 'Kipstoof: een winterse maaltijd', 'Winterse stoofpot met kip'),
  ('https://miljuschka.nl/zalmburgers-recept/', 'Zalmburgers in een krokant jasje, met pittige saus', 'Krokante zalmburgers met pittige saus'),
  ('https://miljuschka.nl/gezonde-traybake-met-zalm/', 'Gezonde traybake met zalm', 'Zalm met aardappel, courgette en broccoli van de bakplaat'),
  ('https://miljuschka.nl/vegetarische-thaise-curry-met-kikkererwten/', 'Vegetarische Thaise curry met kikkererwten', 'Thaise kikkererwtencurry uit één pan (vega)'),
  ('https://miljuschka.nl/thaise-groene-curry-met-garnalen-makkelijk-recept/', 'Thaise groene curry met garnalen', 'Groene Thaise garnalencurry'),
  ('https://miljuschka.nl/kip-met-rijst-een-aziatische-twist/', 'Kip met rijst: een Aziatische twist', 'Aziatische kip met rijst'),
  ('https://miljuschka.nl/budget-koken-curry-van-zoete-aardappel-en-kikkererwten/', 'Curry met zoete aardappel en kikkererwten', 'Kikkererwtencurry met zoete aardappel'),
  ('https://miljuschka.nl/de-ultieme-lasagne/', 'De ultieme lasagne', 'Lasagne bolognese met ricotta en mozzarella'),
  ('https://miljuschka.nl/koffie-stoofvlees-met-pasta-en-gremolata/', 'Koffie stoofvlees met pasta en gremolata', 'Stoofvlees met koffie, pasta en gremolata'),
  ('https://miljuschka.nl/aardbei-burrata-salade/', 'Aardbei-burratasalade', 'Salade met aardbei en burrata'),
  ('https://miljuschka.nl/airfryer-quesadillas-met-kruidensla/', 'Airfryer-quesadilla''s met kruidensla', 'Quesadilla''s uit de airfryer met kruidensla'),
  ('https://miljuschka.nl/aubergine-schnitzel/', 'Auberginschnitzels', 'Schnitzels van aubergine'),
  ('https://miljuschka.nl/auberginestoof-met-geroosterde-kip-uit-de-airfryer/', 'Auberginestoof met geroosterde kip uit de airfryer', 'Auberginestoof met kip uit de airfryer'),
  ('https://miljuschka.nl/babi-pangang/', 'Babi pangang', 'Babi pangang met zoete ananassaus'),
  ('https://miljuschka.nl/balinese-sate-babi-met-sambal-mbe/', 'Balinese saté babi met sambal mbe', 'Saté babi op Balinese wijze met sambal mbe'),
  ('https://miljuschka.nl/basis-aspergesoep/', 'Basis aspergesoep', 'Eenvoudige soep van witte asperges'),
  ('https://miljuschka.nl/bbq-spiesen-met-coquilles-reuzegarnalen-dressing-van-limoen/', 'BBQ-spiesen met coquilles, reuzegarnalen en limoendressing', 'Bbq-spiesen met coquilles en garnalen in limoendressing'),
  ('https://miljuschka.nl/beef-wellington-met-ossenhaas-recept/', 'Beef Wellington met ossenhaas', 'Beef Wellington van ossenhaas'),
  ('https://miljuschka.nl/beenham-uit-de-oven-met-kruidnagel-cranberry-portglazuur/', 'Beenham uit de oven met kruidnagel en cranberry-portglazuur', 'Ovenbeenham met kruidnagel en glazuur van cranberry en port'),
  ('https://miljuschka.nl/beet-wellington-een-vegetarische-variant-op-beef-wellington/', 'Beet Wellington (vegetarische variant)', 'Beet Wellington: Wellington met biet'),
  ('https://miljuschka.nl/biersoep-met-venkel/', 'Biersoep met venkel', 'Venkelsoep met donker bier'),
  ('https://miljuschka.nl/birria-tacos/', 'Birria-taco''s', 'Taco''s met birria'),
  ('https://miljuschka.nl/boerenkoolrisotto/', 'Boerenkoolrisotto', 'Risotto met boerenkool en blauwe kaas'),
  ('https://miljuschka.nl/broccoli-pasta-met-mozzarella-en-citroen/', 'Broccolipasta met mozzarella en citroen', 'Pasta met broccoli, mozzarella en citroen'),
  ('https://miljuschka.nl/burrito-met-kip-zwarte-bonen-en-tomatensla/', 'Burrito met kip, zwarte bonen en tomatensalsa', 'Kipburrito met zwarte bonen en tomatensalsa'),
  ('https://miljuschka.nl/burrito-recept/', 'Burrito''s met rundergehakt', 'Burrito''s met gehakt'),
  ('https://miljuschka.nl/caesar-pasta-salade/', 'Caesar pastasalade', 'Pastasalade in caesarstijl'),
  ('https://miljuschka.nl/caesar-salade-met-een-twist-geroosterde-little-gem-crispy-kipschnitzel/', 'Caesarsalade met geroosterde little gem en crispy kipschnitzel', 'Caesarsalade met krokante kipschnitzel en geroosterde little gem'),
  ('https://miljuschka.nl/cheezy-eenpans-lasagne/', 'Cheezy eenpans lasagne', 'Lasagne met veel kaas uit één pan'),
  ('https://miljuschka.nl/chili-con-carne/', 'Chili con carne met koffie', 'Chili con carne met een scheut koffie'),
  ('https://miljuschka.nl/courgette-lasagne-recept/', 'Courgette lasagne', 'Lasagne van courgette met ricotta en spinazie'),
  ('https://miljuschka.nl/courgettesoep-met-hollandse-garnalen-recept/', 'Courgettesoep met Hollandse garnalen', 'Soep van courgette met Hollandse garnalen'),
  ('https://miljuschka.nl/crispy-zalm-bowl/', 'Crispy zalm bowl', 'Rijstbowl met krokante zalm en avocado'),
  ('https://miljuschka.nl/croque-monsieur/', 'Croque monsieur', 'Croque monsieur met bechamel'),
  ('https://miljuschka.nl/crunchy-wrap-met-kipgehakt/', 'Crunchy wrap met kipgehakt', 'Krokante wrap met kipgehakt'),
  ('https://miljuschka.nl/curry-met-kipballetjes-en-volop-proteine/', 'Curry met kipballetjes en volop proteïne', 'Eiwitrijke curry met kipballetjes'),
  ('https://miljuschka.nl/de-makkelijkste-pasta-ooit-in-een-pan/', 'De makkelijkste romige groene pasta ooit', 'Snelle romige groene pasta'),
  ('https://miljuschka.nl/de-perfecte-nasi-goreng-om-thuis-te-maken/', 'Eenvoudig nasi goreng recept', 'Simpele nasi goreng'),
  ('https://miljuschka.nl/eenpans-curry-noedels-binnen-15-minuten/', 'Eenpans curry noedels binnen 15 minuten', 'Currynoedels uit één pan in 15 minuten'),
  ('https://miljuschka.nl/eenpans-doperwtenstoof-met-lam/', 'Eenpans-doperwtenstoof met lam', 'Lamsstoof met doperwten uit één pan'),
  ('https://miljuschka.nl/eenpans-pasta-pesto/', 'Eenpans pasta pesto', 'Farfalle met pesto, kip en broccoli uit één pan'),
  ('https://miljuschka.nl/eenpans-romige-groentesoep/', 'Eenpans romige groentesoep', 'Romige groentesoep uit één pan'),
  ('https://miljuschka.nl/eenpans-tandoori/', 'Eenpans tandoori', 'Tandoori-kip uit één pan'),
  ('https://miljuschka.nl/eenpans-udon-noedels-met-garnalen/', 'Eenpans udon noedels met garnalen', 'Udonnoedels met garnalen uit één pan'),
  ('https://miljuschka.nl/eenpansgerecht-creamy-orzo/', 'Eenpansgerecht creamy orzo', 'Romige orzo met kikkererwten uit één pan'),
  ('https://miljuschka.nl/eenpansgerecht-enchiladas/', 'Eenpansgerecht enchiladas', 'Kip-enchiladas uit één pan'),
  ('https://miljuschka.nl/eenpansgerecht-met-orzo-en-zalm/', 'Eenpansgerecht met orzo en zalm', 'Orzo met zalm uit één pan'),
  ('https://miljuschka.nl/eenpansgerecht-met-rigatoni-chorizo-en-mozzarella/', 'Eenpansgerecht met rigatoni, chorizo en mozzarella', 'Rigatoni met chorizo en mozzarella uit één pan'),
  ('https://miljuschka.nl/eenpansgerecht-pompoen-pasta/', 'Eenpansgerecht pompoen pasta', 'Pompoenpasta met ''nduja uit één pan'),
  ('https://miljuschka.nl/eenpansgerecht-romige-kip-cajun/', 'Eenpansgerecht romige kip cajun', 'Romige cajunkip uit één pan'),
  ('https://miljuschka.nl/eenpansgerecht-romige-pasta-met-prei-en-burrata/', 'Eenpansgerecht romige pasta met prei en burrata', 'Romige pasta met prei en burrata uit één pan'),
  ('https://miljuschka.nl/eenpanslasagne-met-kip-broccoli-en-kaas/', 'Eenpanslasagne met kip, broccoli en kaas', 'Lasagne met kip, broccoli en kaas uit één pan'),
  ('https://miljuschka.nl/eenpanspasta-bolognese-uit-de-airfryer/', 'Eenpanspasta bolognese uit de airfryer', 'Airfryer-pasta bolognese uit één bak'),
  ('https://miljuschka.nl/eenpanspasta-orechiette-met-feta-en-olijven/', 'Eenpanspasta: orecchiette met feta en olijven', 'Orecchiette met feta en olijven uit één pan'),
  ('https://miljuschka.nl/eenpansrijst-met-kipsate/', 'Eenpansrijst met kipsaté', 'Rijst met kipsaté uit één pan'),
  ('https://miljuschka.nl/eikhaassteak-met-polenta-en-regenboog-snijbiet/', 'Eikhaassteak met polenta en regenboog snijbiet', 'Steak van eikhaas met polenta en regenboogsnijbiet'),
  ('https://miljuschka.nl/eiwitrijke-romige-tomatensoep/', 'Eiwitrijke romige tomatensoep', 'Romige tomatensoep met extra eiwit'),
  ('https://miljuschka.nl/exclusief-voor-jou-rijstnoedels-met-bouillon/', 'Rijstnoedels met koolsalade en bouillon', 'Rijstnoedels in bouillon met koolsalade'),
  ('https://miljuschka.nl/fajitas-met-bavette/', 'Fajitas met bavette', 'Bavette-fajitas met paprika'),
  ('https://miljuschka.nl/fajitas-met-kip-uit-de-airfryer/', 'Fajitas met kip uit de airfryer', 'Airfryer-fajitas met kip'),
  ('https://miljuschka.nl/foe-yong-hai/', 'Foe yong hai', 'Foe yong hai met kip en groenten'),
  ('https://miljuschka.nl/french-onion-pasta/', 'French onion pasta', 'Pasta in de stijl van Franse uiensoep'),
  ('https://miljuschka.nl/frisse-aziatische-omelet-met-garnalen/', 'Frisse Aziatische omelet met garnalen', 'Aziatische garnalenomelet, lekker fris'),
  ('https://miljuschka.nl/frisse-thaise-noedelsalade/', 'Frisse Thaise noedelsalade', 'Thaise noedelsalade met kip en verse kruiden'),
  ('https://miljuschka.nl/gado-gado-look-a-like-met-edamame/', 'Gado gado look-a-like met edamame', 'Salade in gado-gadostijl met edamame'),
  ('https://miljuschka.nl/gamba-spiesjes-met-frisse-mais-avocadosalade-van-de-bbq/', 'Gamba spiesjes met frisse mais-avocadosalade van de bbq', 'Gambaspiesjes van de bbq met mais-avocadosalade'),
  ('https://miljuschka.nl/gambas-van-de-barbecue/', 'Gambas van de barbecue', 'Gegrilde gamba''s van de bbq'),
  ('https://miljuschka.nl/gele-curry-met-vis-zoete-aardappel-en-wortel/', 'Gele curry met vis, zoete aardappel en wortel', 'Gele viscurry met zoete aardappel en wortel'),
  ('https://miljuschka.nl/geroosterde-kip-met-kaneel-en-sinaasappel/', 'Geroosterde kip met kaneel en sinaasappel', 'Kip uit de oven met kaneel en sinaasappel'),
  ('https://miljuschka.nl/geroosterde-wortelsalade/', 'Geroosterde wortelsalade', 'Salade van geroosterde wortel met yoghurt'),
  ('https://miljuschka.nl/gestoofde-kip-in-pindasaus-met-pompoen-en-paprika/', 'Gestoofde kip in pindasaus met pompoen en paprika', 'Kipstoof in pindasaus met pompoen en paprika'),
  ('https://miljuschka.nl/gestoofde-kip-met-druiven-en-sinaasappel/', 'Gestoofde kip met druiven en sinaasappel', 'Kipstoof met druiven en sinaasappel'),
  ('https://miljuschka.nl/gevulde-paprika/', 'Gevulde paprika', 'Gevulde paprika met rijst en kipgehakt'),
  ('https://miljuschka.nl/gevulde-pompoen-met-gemengde-rijst-en-paddenstoelen/', 'Gevulde pompoen met gemengde rijst en paddenstoelen', 'Pompoen gevuld met gemengde rijst en paddenstoelen'),
  ('https://miljuschka.nl/gezonde-proteine-bowl-uit-de-airfryer/', 'Gezonde proteïne bowl uit de Airfryer', 'Eiwitrijke bowl met zoete aardappel en kipgehakt uit de airfryer'),
  ('https://miljuschka.nl/gezonde-quinoa-bowl/', 'Gezonde quinoa bowl', 'Quinoabowl met komkommer en tomaat'),
  ('https://miljuschka.nl/gezonde-tonijnsalade-bagel/', 'Gezonde tonijnsalade met zelfgemaakte bagels', 'Tonijnsalade met zelfgebakken bagels'),
  ('https://miljuschka.nl/gezonde-winterse-groentestoof/', 'Gezonde winterse groentestoof', 'Winterse groentestoof met kikkererwten en harissa'),
  ('https://miljuschka.nl/gnocchi-carbonara-met-knoflookbrood-uit-de-airfryer/', 'Gnocchi Carbonara met knoflookbrood uit de Airfryer', 'Airfryer-gnocchi carbonara met knoflookbrood'),
  ('https://miljuschka.nl/goulashsoep-met-gnocchi/', 'Goulashsoep met gnocchi', 'Stevige goulashsoep met gnocchi'),
  ('https://miljuschka.nl/groene-currysoep-met-garnalen-en-noedels/', 'Groene currysoep met garnalen en noedels', 'Groene currysoep met noedels en garnalen'),
  ('https://miljuschka.nl/groene-pasta-met-miso-citroensaus-uit-de-airfryer/', 'Groene pasta met miso-citroensaus uit de Airfryer', 'Airfryer-pasta in groene miso-citroensaus'),
  ('https://miljuschka.nl/gyoza-noedelsoep-uit-de-aifryer/', 'Gyoza noedelsoep uit de Airfryer', 'Noedelsoep met gyoza uit de airfryer'),
  ('https://miljuschka.nl/gyoza-soep/', 'Gyoza soep', 'Kokos-currysoep met gyoza'),
  ('https://miljuschka.nl/heerlijk-frisse-lente-minestrone/', 'Heerlijk frisse lente minestrone', 'Frisse minestrone met lentegroenten'),
  ('https://miljuschka.nl/huzarensalade/', 'Huzarensalade', 'Huzarensalade met rookvlees en appel'),
  ('https://miljuschka.nl/indiase-butter-chicken/', 'Indiase butter chicken', 'Butter chicken op Indiase wijze'),
  ('https://miljuschka.nl/indiase-keema-curry-met-komkommerraita/', 'Indiase keema curry met komkommerraita', 'Keema-curry met komkommerraita'),
  ('https://miljuschka.nl/indiase-vegan-curry-recept/', 'Indiase vegan curry', 'Vegan Indiase linzencurry'),
  ('https://miljuschka.nl/italiaans-stoofpotje-met-kip-venkel-en-kalamataolijven/', 'Italiaans stoofpotje met kip, venkel en kalamataolijven', 'Italiaanse kipstoof met venkel en kalamata-olijven'),
  ('https://miljuschka.nl/italiaanse-andijviestamppot/', 'Italiaanse andijviestamppot', 'Andijviestamppot op z''n Italiaans'),
  ('https://miljuschka.nl/japanse-nasi-met-edamame/', 'Japanse nasi met edamame', 'Japanse nasi met edamame, minimais en shiitake'),
  ('https://miljuschka.nl/katsu-curry-met-kipschnitzel/', 'Katsu curry met kipschnitzel', 'Kipschnitzel met katsu-curry'),
  ('https://miljuschka.nl/kip-champignonsoep-een-heerlijke-maaltijdsoep/', 'Kip champignonsoep', 'Maaltijdsoep met kip en champignons'),
  ('https://miljuschka.nl/kip-harissa-pasta-uit-de-airfryer/', 'Kip-harissa-pasta uit de airfryer', 'Airfryer-pasta met kip en harissa'),
  ('https://miljuschka.nl/kip-shoarma-rol/', 'Kip shoarma rol', 'Rol met kipshoarma'),
  ('https://miljuschka.nl/kiprollade/', 'Kiprollade', 'Kiprollade met krieltjes en bospeen'),
  ('https://miljuschka.nl/klassieke-foe-yong-hai-de-allerlekkerste/', 'Klassieke foe yong hai', 'Foe yong hai, de klassieker'),
  ('https://miljuschka.nl/klassieke-quiche-lorraine/', 'Klassieke quiche Lorraine', 'Quiche Lorraine met gerookt spek'),
  ('https://miljuschka.nl/klassieke-spaghetti-puttanesca/', 'Klassieke spaghetti puttanesca', 'Spaghetti alla puttanesca'),
  ('https://miljuschka.nl/koken-uit-de-voorraadkast-risotto-met-paddenstoelen/', 'Risotto met paddenstoelen', 'Paddenstoelenrisotto uit de voorraadkast'),
  ('https://miljuschka.nl/koreaanse-fried-chicken-bowl/', 'Koreaanse fried chicken bowl', 'Bowl met Koreaanse krokante kip'),
  ('https://miljuschka.nl/leftover-kerst-pho-van-kalkoen/', 'Leftover kerst pho van kalkoen', 'Pho van kalkoenrestjes na kerst'),
  ('https://miljuschka.nl/lekker-frisse-citrussalade-met-burrata/', 'Lekker frisse citrussalade met burrata', 'Frisse salade van citrus en burrata'),
  ('https://miljuschka.nl/lekker-verfrissend-gazpacho/', 'Lekker verfrissende gazpacho', 'Verfrissende gazpacho met geroosterde paprika'),
  ('https://miljuschka.nl/lente-pizza-met-bonenspread/', 'Lente pizza met bonenspread', 'Lentepizza met bonenspread'),
  ('https://miljuschka.nl/linzen-spinaziecurry-met-champignons-en-ei/', 'Linzen-spinaziecurry met champignons en ei', 'Curry van linzen en spinazie met champignons en ei'),
  ('https://miljuschka.nl/linzencurry-met-garnalen/', 'Linzencurry met garnalen', 'Garnalen in linzencurry'),
  ('https://miljuschka.nl/makkelijke-eenpanspasta-met-worst/', 'Makkelijke eenpanspasta met worst', 'Simpele worstpasta uit één pan'),
  ('https://miljuschka.nl/massaman-curry-met-sperziebonen/', 'Massaman curry met sperziebonen', 'Massamancurry met sperzieboontjes'),
  ('https://miljuschka.nl/mexicaanse-burrito-bowl-meal-prep/', 'Mexicaanse burrito bowl meal prep', 'Mexicaanse burritobowl om te mealpreppen'),
  ('https://miljuschka.nl/mexicaanse-eenpanstopper-met-zoete-aardappel/', 'Mexicaanse eenpanstopper met zoete aardappel', 'Mexicaanse eenpansschotel met zoete aardappel en nacho''s'),
  ('https://miljuschka.nl/mexicaanse-taco-bowl/', 'Mexicaanse taco bowl', 'Mexicaanse tacobowl met rundergehakt'),
  ('https://miljuschka.nl/miljuschkas-nasi-goreng/', 'Miljuschka''s nasi goreng', 'Nasi goreng van het huis'),
  ('https://miljuschka.nl/miljuschkas-snelle-ramen/', 'Miljuschka''s snelle ramen', 'Snelle ramen met paksoi en oesterzwammen'),
  ('https://miljuschka.nl/mosterdsoep/', 'Mosterdsoep', 'Romige mosterdsoep met een scheutje sherry'),
  ('https://miljuschka.nl/nachos-met-kaas/', 'Nacho''s met kaas', 'Nacho''s met gehakt en gesmolten kaas'),
  ('https://miljuschka.nl/nasi-goreng-met-spitskool-serundeng-eitjes/', 'Nasi goreng met spitskool en serundeng-eitjes', 'Nasi goreng met spitskool en eitjes met serundeng'),
  ('https://miljuschka.nl/nasi-goreng-van-bloemkoolrijst-en-garnalen/', 'Nasi goreng van bloemkoolrijst en garnalen', 'Bloemkoolrijst-nasi met garnalen'),
  ('https://miljuschka.nl/nasi-met-tempeh-champignons-en-bladgroente/', 'Nasi met tempeh, champignons en bladgroente', 'Nasi met tempeh, champignons en bladgroenten'),
  ('https://miljuschka.nl/okonomiyaki-recept-japanse-hartige-pannenkoek/', 'Okonomiyaki (Japanse hartige pannenkoek)', 'Okonomiyaki, hartige Japanse pannenkoek'),
  ('https://miljuschka.nl/open-lasagne-met-boontjes-burrata-en-salieboter/', 'Open lasagne met boontjes, burrata en salieboter', 'Open lasagne met burrata, boontjes en salieboter'),
  ('https://miljuschka.nl/ossenstaartsoep/', 'Ossenstaartsoep', 'Ossenstaartsoep met rode wijn'),
  ('https://miljuschka.nl/ossobuco-alla-milanese/', 'Ossobuco alla Milanese', 'Ossobuco op Milanese wijze'),
  ('https://miljuschka.nl/oud-hollandse-gehaktballen/', 'Oud-Hollandse gehaktballen', 'Gehaktballen op oud-Hollandse wijze'),
  ('https://miljuschka.nl/paella-met-kip-en-vis/', 'Paella met kip en vis', 'Paella met vis en kip'),
  ('https://miljuschka.nl/panzanella-een-heerlijke-italiaanse-broodsalade/', 'Panzanella: een heerlijke Italiaanse broodsalade', 'Panzanella, de Italiaanse broodsalade'),
  ('https://miljuschka.nl/papardelle-met-runderragu-marije-knevel/', 'Pappardelle met langzaam gegaarde Italiaanse runderragù', 'Pappardelle met langzaam gestoofde runderragù'),
  ('https://miljuschka.nl/paprikasoep-recept/', 'Paprikasoep', 'Paprikasoep met feta en gerookt paprikapoeder'),
  ('https://miljuschka.nl/paratha-met-frisse-salade-en-spiegelei/', 'Paratha met frisse salade en spiegelei', 'Paratha met spiegelei en frisse salade'),
  ('https://miljuschka.nl/pasta-al-forno/', 'Pasta al forno met kip en paddenstoelen', 'Pasta al forno met paddenstoelen en kip'),
  ('https://miljuschka.nl/pasta-alfredo/', 'Pasta Alfredo', 'Fettuccine Alfredo met gepaneerde kip'),
  ('https://miljuschka.nl/pasta-arrabbiata/', 'Pasta arrabbiata', 'Spaghetti all''arrabbiata'),
  ('https://miljuschka.nl/pasta-carbonara-taart/', 'Pasta carbonara taart', 'Carbonarataart van spaghetti'),
  ('https://miljuschka.nl/pasta-met-prei-ui-en-ansjovis-uit-de-airfryer/', 'Pasta met prei, ui en ansjovis uit de airfryer', 'Airfryer-pasta met prei, ui en ansjovis'),
  ('https://miljuschka.nl/pasta-met-zalm/', 'Pasta met zalm', 'Tagliatelle met zalm in tomaten-roomsaus'),
  ('https://miljuschka.nl/pasta-pesto-met-tomaatjes-en-parmezaanse-kaas/', 'Pasta pesto met tomaatjes en Parmezaanse kaas', 'Pasta pesto met Parmezaan en tomaatjes'),
  ('https://miljuschka.nl/pasta-recept-in-15-minuten-pasta-met-tomaat-en-burrata/', 'Pasta in 15 minuten met tomaat en burrata', 'Pasta met tomaat en burrata in 15 minuten'),
  ('https://miljuschka.nl/pastasalade-met-artisjok-en-ansjovis-dressing/', 'Pastasalade met artisjok en ansjovisdressing', 'Pastasalade met artisjok en dressing van ansjovis'),
  ('https://miljuschka.nl/pastasalade-met-garnalen-avocado-en-cocktailsaus/', 'Pastasalade met garnalen, avocado en cocktailsaus', 'Pastasalade met avocado, garnalen en cocktailsaus'),
  ('https://miljuschka.nl/pittige-10-minuten-noedels/', 'Pittige 10-minuten-noedels', 'Pittige noedels in 10 minuten'),
  ('https://miljuschka.nl/plantaardige-bastilla-recept/', 'Plantaardige bastilla', 'Vegan bastilla met linzen'),
  ('https://miljuschka.nl/poke-bowl-met-spicy-tuna/', 'Poke bowl met spicy tuna', 'Pokébowl met pittige tonijn'),
  ('https://miljuschka.nl/pompoensalade-met-linzen-en-boerenkool/', 'Pompoensalade met linzen en boerenkool', 'Salade van pompoen, linzen en boerenkool'),
  ('https://miljuschka.nl/pompoensoep-franse-stijl/', 'Pompoensoep Franse stijl', 'Pompoensoep op z''n Frans'),
  ('https://miljuschka.nl/pulled-chicken-tacos/', 'Pulled chicken taco''s', 'Taco''s met pulled chicken'),
  ('https://miljuschka.nl/pulled-chicken-wraps/', 'Pulled chicken wraps', 'Wraps met pulled chicken'),
  ('https://miljuschka.nl/quesedilla-pulled-chicken-tomatenrelish/', 'Quesadilla met pulled chicken en tomatenrelish', 'Quesadilla met tomatenrelish en pulled chicken'),
  ('https://miljuschka.nl/quiche-met-spinazie-en-spek/', 'Quiche met spinazie en spek', 'Quiche met spek en spinazie'),
  ('https://miljuschka.nl/ramen-noodle-bowl/', 'Ramen noedel bowl', 'Ramenbowl met kip en shiitake'),
  ('https://miljuschka.nl/ratatouille-op-mijn-manier/', 'Ratatouille op mijn manier', 'Ratatouille uit de oven'),
  ('https://miljuschka.nl/recept-van-donna-hay-radicchiosalade-met-ingelegde-nectarine/', 'Radicchiosalade met ingelegde nectarine', 'Salade van radicchio met ingelegde nectarine'),
  ('https://miljuschka.nl/recept-voor-chicken-karaage/', 'Chicken karaage: krokante Japanse kip', 'Karaage: Japanse krokante kip'),
  ('https://miljuschka.nl/rendang-van-pulled-kippendij/', 'Rendang van pulled kippendij', 'Rendang van uitgeplozen kippendij'),
  ('https://miljuschka.nl/ribeye-tacos-met-koffie-rub-en-zelfgemaakte-koffie-bbq-saus/', 'Ribeye taco''s met koffie rub en zelfgemaakte koffie bbq-saus', 'Taco''s met ribeye, koffierub en huisgemaakte koffie-bbq-saus'),
  ('https://miljuschka.nl/rode-curry-met-gehaktballen-uit-de-airfryer/', 'Rode curry met gehaktballen uit de airfryer', 'Rode curry met gehaktballetjes uit de airfryer'),
  ('https://miljuschka.nl/rode-curry-met-sinaasappel-en-geroosterde-kwartel/', 'Rode curry met sinaasappel en geroosterde kwartel', 'Geroosterde kwartel met rode curry en sinaasappel'),
  ('https://miljuschka.nl/romig-eenpansgerecht-met-pasta-en-groene-asperges/', 'Romig eenpansgerecht met pasta en groene asperges', 'Romige eenpanspasta met groene asperges'),
  ('https://miljuschka.nl/romige-champignonsoep/', 'Romige champignonsoep', 'Romige paddenstoelensoep met tijm'),
  ('https://miljuschka.nl/romige-kip-enchiladas/', 'Romige kip enchilada''s', 'Romige enchilada''s met kip'),
  ('https://miljuschka.nl/romige-oosterse-pompoensoep-recept/', 'Romige oosterse pompoensoep', 'Romige pompoensoep met oosterse smaken'),
  ('https://miljuschka.nl/romige-pasta-met-paprika-en-tomaat-pasta-voor-kinderen/', 'Romige pasta met paprika en tomaat - pasta voor kinderen', 'Kindvriendelijke romige pasta met paprika en tomaat'),
  ('https://miljuschka.nl/romige-pasta-pesto-salade-vega/', 'Romige pasta pesto salade (vega)', 'Vegetarische pastasalade met romige pesto'),
  ('https://miljuschka.nl/romige-venkelsoep-recept/', 'Romige venkelsoep met prei', 'Romige soep van venkel en prei'),
  ('https://miljuschka.nl/roti-bowl-met-crispy-kip/', 'Roti bowl met crispy kip', 'Rotibowl met krokante kip'),
  ('https://miljuschka.nl/salade-caprese/', 'Salade caprese', 'Caprese met buffelmozzarella en balsamico'),
  ('https://miljuschka.nl/salade-nicoise-met-citroenkrieltjes/', 'Salade Niçoise met citroenkrieltjes', 'Niçoise-salade met citroenkrieltjes'),
  ('https://miljuschka.nl/salade-van-courgette-en-komkommerlinten-met-granaatappelpitten-feta-en-munt-walnootpesto/', 'Salade van courgette- en komkommerlinten met granaatappelpitten, feta en munt-walnootpesto', 'Linten van courgette en komkommer met feta, granaatappel en munt-walnootpesto'),
  ('https://miljuschka.nl/sate-ayam-met-pittige-pindasaus-en-atjar-ketimoen/', 'Saté ayam met pittige pindasaus en atjar ketimoen', 'Saté ajam met atjar ketimoen en pittige pindasaus'),
  ('https://miljuschka.nl/satecurry/', 'Satécurry', 'Satécurry met kip'),
  ('https://miljuschka.nl/sinterklaas-stoofvlees/', 'Sinterklaas stoofvlees met kruidnoten', 'Stoofvlees met kruidnoten voor Sinterklaas'),
  ('https://miljuschka.nl/slowcooker-runderstoof/', 'De ultieme slowcooker runderstoof', 'Runderstoof uit de slowcooker'),
  ('https://miljuschka.nl/snelle-nasi-met-prei-en-cavolo-nero/', 'Snelle nasi met prei en cavolo nero', 'Vlotte nasi met prei en cavolo nero'),
  ('https://miljuschka.nl/snelle-tacos-met-cajun-garnalen-mango-en-avocado/', 'Snelle taco''s met cajun garnalen, mango en avocado', 'Snelle taco''s met cajungarnalen, avocado en mango'),
  ('https://miljuschka.nl/snert-zo-maak-je-hollandse-erwtensoep/', 'Snert: zo maak je Hollandse erwtensoep', 'Snert, echte Hollandse erwtensoep'),
  ('https://miljuschka.nl/soep-met-courgette-cheddar-en-aardappel/', 'Courgettesoep met doperwten, aardappel en cheddar', 'Courgettesoep met aardappel, doperwten en cheddar'),
  ('https://miljuschka.nl/spinazie-wrap-met-kipfilet/', 'Spinazie wrap met kipfilet', 'Spinaziewrap met kipfilet'),
  ('https://miljuschka.nl/stamppot-savooiekool-met-crispy-indische-speklapjes/', 'Stamppot savooiekool met crispy Indische speklapjes', 'Savooiekoolstamppot met krokante Indische speklapjes'),
  ('https://miljuschka.nl/stoofschotel-met-bokbier/', 'Stoofschotel met bokbier', 'Stoofpot met bokbier'),
  ('https://miljuschka.nl/taco-met-zelfgemaakte-schnitzel/', 'Taco met zelfgemaakte schnitzel', 'Taco met huisgemaakte schnitzel'),
  ('https://miljuschka.nl/tagliatelle-al-tartufo-chantal-janzen/', 'Pasta al tartufo met truffel', 'Pasta met truffel (al tartufo)'),
  ('https://miljuschka.nl/tagliatelle-met-garnalen/', 'Tagliatelle met garnalen', 'Tagliatelle met garnalen in cognac-roomsaus'),
  ('https://miljuschka.nl/thaise-curry-met-zalm-recept/', 'Thaise curry met zalm en kokos', 'Thaise zalmcurry met kokos'),
  ('https://miljuschka.nl/thaise-gestoofde-kip/', 'Thaise gestoofde kip', 'Thaise kipstoof met gele curry'),
  ('https://miljuschka.nl/thaise-groene-curry-met-kalkoen/', 'Thaise groene curry met kalkoen', 'Groene Thaise kalkoencurry'),
  ('https://miljuschka.nl/thaise-rode-curry-nina-pierson/', 'Thaise rode curry met kip', 'Rode Thaise kipcurry'),
  ('https://miljuschka.nl/thaise-slawrap-met-gemarineerde-kip-en-pindadressing/', 'Thaise slawrap met gemarineerde kip en pindadressing', 'Thaise slawrap met pindadressing en gemarineerde kip'),
  ('https://miljuschka.nl/tom-kha-kai-soep/', 'Tom kha kai soep', 'Tom kha kai'),
  ('https://miljuschka.nl/traditionele-rundergoulash/', 'Traditionele rundergoulash', 'Rundergoulash'),
  ('https://miljuschka.nl/traybake-met-zoete-aardappel-en-feta/', 'Traybake met zoete aardappel en feta', 'Traybake met feta en zoete aardappel'),
  ('https://miljuschka.nl/traybake-wraps/', 'Traybake wraps', 'Wraps met kipgehakt van de bakplaat'),
  ('https://miljuschka.nl/uiensoep-met-een-twist/', 'Uiensoep met een twist', 'Uiensoep, net even anders'),
  ('https://miljuschka.nl/uiensoep-recept/', 'Franse uiensoep recept: zo maak je deze klassieke soep', 'Klassieke Franse uiensoep'),
  ('https://miljuschka.nl/ultieme-boeuf-bourguignon/', 'Ultieme Boeuf Bourguignon', 'Boeuf bourguignon'),
  ('https://miljuschka.nl/ultieme-new-yorkse-hot-dog-recept/', 'Ultieme New Yorkse hot dog', 'New Yorkse hotdog'),
  ('https://miljuschka.nl/vega-ramensoep-vegetarische-ramen-noedelsoep/', 'Vega ramensoep met miso-pompoen, shiitake en een eitje', 'Vegetarische ramen met miso-pompoen, shiitake en ei'),
  ('https://miljuschka.nl/vega-thaise-curry-linda-hakeboom/', 'Vega Thaise curry – Linda Hakeboom', 'Vegetarische Thaise curry'),
  ('https://miljuschka.nl/vegetarisch-bbq-gerecht-geroosterde-groenten-barbecue/', 'Vegetarisch BBQ gerecht: geroosterde groenten met kikkererwten', 'Geroosterde groenten met kikkererwten van de bbq'),
  ('https://miljuschka.nl/volkoren-pastasalade-met-erwtjes-en-kip/', 'Volkoren pastasalade met erwtjes en kip', 'Volkoren pastasalade met kip en erwtjes'),
  ('https://miljuschka.nl/volkorenwraps-met-honing-mosterdkip-en-spinazie/', 'Volkorenwraps met honing-mosterdkip en spinazie', 'Volkorenwraps met spinazie en honing-mosterdkip'),
  ('https://miljuschka.nl/winterse-lasagne-met-groene-groenten/', 'Winterse lasagne met groene groenten', 'Winterlasagne met groene groenten'),
  ('https://miljuschka.nl/witlof-met-ham-en-kaassaus/', 'Witlof met ham en kaassaus', 'Witlof in kaassaus met ham'),
  ('https://miljuschka.nl/witte-aspergesoep/', 'Witte aspergesoep', 'Soep van witte asperges met ei en ham'),
  ('https://miljuschka.nl/wraps-met-gehakt/', 'Wraps met gehakt', 'Wraps met rundergehakt en bonen'),
  ('https://miljuschka.nl/zelf-turkse-pizza-maken-lahmacun/', 'Zelf Turkse pizza maken – Lahmacun', 'Lahmacun: zelfgemaakte Turkse pizza'),
  ('https://miljuschka.nl/zoete-aardappelsoep-met-chilivlokken/', 'Zoete aardappelsoep met chilivlokken', 'Soep van zoete aardappel met chilivlokken'),
  ('https://miljuschka.nl/zoete-aubergine-met-fried-rice-uit-de-airfryer-met-komkommersalade/', 'Zoete aubergine met fried rice uit de airfryer met komkommersalade', 'Zoete aubergine met gebakken rijst en komkommersalade uit de airfryer'),
  ('https://miljuschka.nl/zoetzure-noedels-met-ananas/', 'Zoetzure noedels met ananas', 'Noedels in zoetzuur met ananas'),
  ('https://miljuschka.nl/zomerse-slowcooker-recept-tostada-met-pulled-pork/', 'Zomerse slowcooker recept: tostada met pulled pork', 'Tostada met pulled pork uit de slowcooker'),
  ('https://uitpaulineskeuken.nl/recept/aubergine-schnitzel', 'Aubergine schnitzel', 'Schnitzel van aubergine met koolsalade'),
  ('https://uitpaulineskeuken.nl/recept/bastilla', 'Bastilla met pompoen en gekarameliseerde ui', 'Pompoenbastilla met gekarameliseerde ui'),
  ('https://uitpaulineskeuken.nl/recept/confit-de-canard', 'Confit de canard', 'Confit de canard met rode kool'),
  ('https://uitpaulineskeuken.nl/recept/courgette-ovenschotel', 'Courgette ovenschotel', 'Courgetteschotel uit de oven met ricotta en mozzarella'),
  ('https://uitpaulineskeuken.nl/recept/gyoza-salade', 'Gyoza salade', 'Salade met gyoza en edamame'),
  ('https://uitpaulineskeuken.nl/recept/homemade-falafel', 'Zelf falafel maken', 'Zelfgemaakte falafel'),
  ('https://uitpaulineskeuken.nl/recept/indonesische-aubergine', 'Indonesische aubergine', 'Aubergine op Indonesische wijze met rijst'),
  ('https://uitpaulineskeuken.nl/recept/jian-bing', 'Jian bing', 'Jian bing, Chinese gevulde pannenkoek'),
  ('https://uitpaulineskeuken.nl/recept/kip-pesto-lasagne', 'Kip pesto lasagne', 'Lasagne met kip en pesto'),
  ('https://uitpaulineskeuken.nl/recept/koolhydraatarme-ovenschotel-met-gehakt', 'Koolhydraatarme ovenschotel met gehakt', 'Koolhydraatarme gehaktschotel uit de oven'),
  ('https://uitpaulineskeuken.nl/recept/koreaanse-pannenkoek', 'Koreaanse pannenkoek', 'Koreaanse pannenkoek met kimchi'),
  ('https://uitpaulineskeuken.nl/recept/lasagne-met-pompoen', 'Lasagne met pompoen', 'Pompoenlasagne met spinazie'),
  ('https://uitpaulineskeuken.nl/recept/makkelijke-maaltijd-eenpans-pasta', 'Eenpans pasta', 'Pasta met paprika en mascarpone uit één pan'),
  ('https://uitpaulineskeuken.nl/recept/noedels-met-garnalen', 'Gewokte garnalen met noedels', 'Noedels met gewokte garnalen'),
  ('https://uitpaulineskeuken.nl/recept/orzo-ovenschotel', 'Orzo ovenschotel', 'Orzoschotel uit de oven met verse worst'),
  ('https://uitpaulineskeuken.nl/recept/plaattaart-groene-asperges', 'Plaattaart met groene asperges', 'Groene-aspergeplaattaart'),
  ('https://uitpaulineskeuken.nl/recept/ravioli-lasagne', 'Ravioli lasagne', 'Lasagne van ravioli'),
  ('https://uitpaulineskeuken.nl/recept/rosti-ovenschotel', 'Rosti ovenschotel', 'Röstischotel uit de oven met spek en sperziebonen'),
  ('https://uitpaulineskeuken.nl/recept/soep-met-tortellini', 'Soep met tortellini', 'Tomatensoep met tortellini'),
  ('https://uitpaulineskeuken.nl/recept/stamppot-palmkool', 'Stamppot palmkool', 'Palmkoolstamppot met oesterzwammen'),
  ('https://uitpaulineskeuken.nl/recept/taco-salade', 'Taco salade', 'Tacosalade met gehakt en avocado'),
  ('https://uitpaulineskeuken.nl/recept/truffel-kaasfondue', 'Truffel kaasfondue', 'Kaasfondue met truffel'),
  ('https://uitpaulineskeuken.nl/recept/vegetarische-gnocchi', 'Vegetarische gnocchi met pompoensaus', 'Vegetarische gnocchi in pompoensaus'),
  ('https://uitpaulineskeuken.nl/recept/vis-ovenschotel', 'Vis ovenschotel', 'Ovenschotel met kabeljauw en spinazie'),
  ('https://uitpaulineskeuken.nl/recept/zoete-aardappel-prei-stamppot', 'Zoete aardappel prei stamppot', 'Stamppot van zoete aardappel en prei'),
  ('https://uitpaulineskeuken.nl/recept/zuurkoolschotel-met-gehakt', 'Zuurkoolschotel met gehakt', 'Zuurkool-ovenschotel met gehakt en ananas'),
  ('https://uitpaulineskeuken.nl/recept/bieten-quiche', 'Bieten quiche', 'Quiche met rode biet en geitenkaas'),
  ('https://uitpaulineskeuken.nl/recept/cacio-e-pepe', 'Cacio e pepe', 'Spaghetti cacio e pepe'),
  ('https://uitpaulineskeuken.nl/recept/filodeeg-plaattaart-met-tomaten', 'Filodeeg plaattaart met tomaten', 'Plaattaart van filodeeg met tomaat'),
  ('https://uitpaulineskeuken.nl/recept/gegrilde-asperges', 'Gegrilde asperges met kruiden-roomsaus', 'Gegrilde asperges in kruiden-roomsaus'),
  ('https://uitpaulineskeuken.nl/recept/gnocchi-met-pompoen', 'Gnocchi met pompoen', 'Gnocchi met pompoen en ricotta'),
  ('https://uitpaulineskeuken.nl/recept/gnocchi-uit-de-airfryer', 'Gnocchi uit de Airfryer', 'Krokante airfryer-gnocchi met tomaatjes'),
  ('https://uitpaulineskeuken.nl/recept/griekse-pastasalade', 'Griekse pastasalade', 'Pastasalade op z''n Grieks met feta'),
  ('https://uitpaulineskeuken.nl/recept/kervelsoep', 'Kervelsoep', 'Kervelsoep met doperwten en ham'),
  ('https://uitpaulineskeuken.nl/recept/kikkererwtensoep', 'Indiase kikkererwtensoep', 'Indiase soep met kikkererwten en pompoen'),
  ('https://uitpaulineskeuken.nl/recept/knolselderij-steak', 'Knolselderij steak met Waldorf-salade', 'Steak van knolselderij met waldorfsalade'),
  ('https://uitpaulineskeuken.nl/recept/kumpir', 'Kumpir: Turkse gevulde aardappelen', 'Kumpir: gevulde aardappel op z''n Turks'),
  ('https://uitpaulineskeuken.nl/recept/lasagne-met-prei', 'Lasagne met prei', 'Preilasagne met gorgonzola en walnoten'),
  ('https://uitpaulineskeuken.nl/recept/ottolenghis-quiche-met-pompoen', 'Ottolenghi&#8217;s quiche met pompoen', 'Pompoenquiche'),
  ('https://uitpaulineskeuken.nl/recept/pappardelle-met-rucola', 'Pappardelle met rucola', 'Pappardelle met rucola, pesto en tomaatjes'),
  ('https://uitpaulineskeuken.nl/recept/pasta-met-palmkool', 'Pasta met palmkool', 'Romige pasta met palmkool en bloemkool'),
  ('https://uitpaulineskeuken.nl/recept/pasta-met-ricotta', 'Pasta met ricotta en tomaat', 'Pasta met tomaat en ricotta'),
  ('https://uitpaulineskeuken.nl/recept/pasta-pesto', 'Pasta pesto', 'Spaghetti met verse pesto en tomaatjes'),
  ('https://uitpaulineskeuken.nl/recept/pastasalade-met-rode-pesto', 'Pastasalade met rode pesto', 'Pastasalade met pesto rosso'),
  ('https://uitpaulineskeuken.nl/recept/ravioli-met-ricotta', 'Ravioli met ricotta', 'Zelfgemaakte ravioli met ricotta'),
  ('https://uitpaulineskeuken.nl/recept/rigatoni-met-tomaat-mascarponesaus', 'Rigatoni met tomaat-mascarponesaus', 'Rigatoni in tomaten-mascarponesaus'),
  ('https://uitpaulineskeuken.nl/recept/rode-wijn-risotto', 'Rode wijn risotto', 'Risotto met rode wijn en paddenstoelen'),
  ('https://uitpaulineskeuken.nl/recept/roerbak-spitskool', 'Roerbak spitskool', 'Roergebakken spitskool met rijst en ei'),
  ('https://uitpaulineskeuken.nl/recept/spinazie-curry', 'Spinazie curry', 'Spinaziecurry met pompoen en kikkererwten'),
  ('https://uitpaulineskeuken.nl/recept/stamppot-boerenkool', 'Stamppot boerenkool met zoete aardappel', 'Boerenkoolstamppot met zoete aardappel'),
  ('https://uitpaulineskeuken.nl/recept/stamppot-rucola', 'Stamppot rucola', 'Rucolastamppot met feta'),
  ('https://uitpaulineskeuken.nl/recept/tahdig', 'Tahdig', 'Tahdig: Perzische rijst met krokante bodem'),
  ('https://uitpaulineskeuken.nl/recept/tortellini-ovenschotel', 'Tortellini ovenschotel', 'Tortellini uit de oven met pesto en mozzarella'),
  ('https://uitpaulineskeuken.nl/recept/vega-butter-chicken', 'Vega butter chicken', 'Vega butter chicken met bloemkool en broccoli'),
  ('https://uitpaulineskeuken.nl/recept/vega-shoarma', 'Vega shoarma van oesterzwammen', 'Oesterzwamshoarma (vega)'),
  ('https://uitpaulineskeuken.nl/recept/vegetarische-goulash', 'Vegetarische goulash', 'Vegetarische goulash met krieltjes en champignons'),
  ('https://uitpaulineskeuken.nl/recept/wonton-soep', 'Wonton soep', 'Wontonsoep met noedels en paksoi'),
  ('https://uitpaulineskeuken.nl/recept/artisjok-salade', 'Artisjok salade', 'Salade met artisjok, linzen en geitenkaas'),
  ('https://uitpaulineskeuken.nl/recept/aspergesoep', 'Aspergesoep', 'Romige soep van witte asperges'),
  ('https://uitpaulineskeuken.nl/recept/bladerdeeg-met-feta-en-spinazie', 'Bladerdeeg met feta en spinazie', 'Bladerdeeg met spinazie en feta'),
  ('https://uitpaulineskeuken.nl/recept/boerenkoolsoep', 'Boerenkoolsoep met mosterd en crème fraîche', 'Soep van boerenkool met mosterd en crème fraîche'),
  ('https://uitpaulineskeuken.nl/recept/broccoli-bloemkoolsoep', 'Broccoli-bloemkoolsoep', 'Soep van broccoli en bloemkool'),
  ('https://uitpaulineskeuken.nl/recept/broccoli-courgettesoep', 'Broccoli courgettesoep', 'Soep van broccoli en courgette'),
  ('https://uitpaulineskeuken.nl/recept/geroosterde-tomatensoep', 'Geroosterde tomatensoep', 'Soep van geroosterde tomaten en paprika'),
  ('https://uitpaulineskeuken.nl/recept/grote-ravioli', 'Grote ravioli met paddenstoelen en truffel', 'Grote ravioli met truffel en paddenstoelen'),
  ('https://uitpaulineskeuken.nl/recept/gyoza-met-kip', 'Gyoza met kip', 'Gyoza gevuld met kip'),
  ('https://uitpaulineskeuken.nl/recept/heldere-champignonsoep', 'Heldere champignonsoep', 'Heldere paddenstoelensoep'),
  ('https://uitpaulineskeuken.nl/recept/kastanjesoep', 'Kastanjesoep', 'Kastanjesoep met knolselderij en salie'),
  ('https://uitpaulineskeuken.nl/recept/koninginnesoep', 'Koninginnesoep', 'Koninginnesoep met kip'),
  ('https://uitpaulineskeuken.nl/recept/pasteitje-zalmragout', 'Pasteitje zalmragout', 'Pasteitje met zalmragout'),
  ('https://uitpaulineskeuken.nl/recept/pastinaak-knolselderijsoep', 'Pastinaak knolselderijsoep', 'Soep van pastinaak en knolselderij'),
  ('https://uitpaulineskeuken.nl/recept/pastinaaksoep-met-salieboter', 'Pastinaaksoep', 'Pastinaaksoep met rozemarijn en amandelen'),
  ('https://uitpaulineskeuken.nl/recept/quiche-lorraine', 'Quiche Lorraine', 'Quiche Lorraine met spek en gruyère'),
  ('https://uitpaulineskeuken.nl/recept/risotto-met-kip', 'Risotto met kip en spinazie', 'Risotto met spinazie en kip'),
  ('https://uitpaulineskeuken.nl/recept/salade-met-gerookte-zalm', 'Salade met gerookte zalm', 'Gerookte-zalmsalade'),
  ('https://uitpaulineskeuken.nl/recept/salmorejo', 'Salmorejo', 'Salmorejo met ei en chorizo'),
  ('https://uitpaulineskeuken.nl/recept/spinazie-quiche', 'Spinazie quiche', 'Spinaziequiche met feta'),
  ('https://uitpaulineskeuken.nl/recept/steak-tartare', 'Steak tartare op 2 manieren: vlees én vega', 'Steak tartare, met vlees én vegetarisch'),
  ('https://uitpaulineskeuken.nl/recept/thaise-broccolisoep', 'Thaise broccolisoep', 'Thaise soep van broccoli en kokos'),
  ('https://uitpaulineskeuken.nl/recept/tomaten-quiche', 'Tomaten quiche', 'Tomatenquiche met geitenkaas'),
  ('https://uitpaulineskeuken.nl/recept/bouillabaisse', 'Bouillabaisse met garnalen', 'Bouillabaisse met garnalen en mosselen'),
  ('https://uitpaulineskeuken.nl/recept/broccolisoep', 'Broccolisoep met kaascroutons', 'Broccolisoep met croutons van kaas'),
  ('https://uitpaulineskeuken.nl/recept/champignonsoep', 'Champignonsoep', 'Champignonsoep met kaasstengels'),
  ('https://uitpaulineskeuken.nl/recept/courgette-paprikasoep', 'Courgette paprikasoep', 'Soep van courgette en paprika'),
  ('https://uitpaulineskeuken.nl/recept/courgettesoep-met-pesto', 'Courgettesoep', 'Courgettesoep met pesto'),
  ('https://uitpaulineskeuken.nl/recept/curry-noedelsoep', 'Curry noedelsoep', 'Noedelsoep met curry en kip'),
  ('https://uitpaulineskeuken.nl/recept/erwtensoep-uit-de-slowcooker', 'Erwtensoep uit de slowcooker', 'Slowcooker-erwtensoep'),
  ('https://uitpaulineskeuken.nl/recept/gazpacho-recept', 'Koude soep met tomaat en paprika', 'Koude tomaten-paprikasoep'),
  ('https://uitpaulineskeuken.nl/recept/gebonden-kippensoep', 'Gebonden kippensoep', 'Gebonden kippensoep met prei'),
  ('https://uitpaulineskeuken.nl/recept/kerriesoep', 'Kerriesoep met prei', 'Preisoep met kerrie en kip'),
  ('https://uitpaulineskeuken.nl/recept/komkommersoep-met-geitenkaas', 'Komkommersoep met geitenkaas', 'Koude komkommersoep met geitenkaas'),
  ('https://uitpaulineskeuken.nl/recept/maaltijdsoep-met-linzen', 'Maaltijdsoep met linzen', 'Linzenmaaltijdsoep met boerenkool'),
  ('https://uitpaulineskeuken.nl/recept/maissoep-recept', 'Maissoep', 'Maissoep met jalapeño en limoen'),
  ('https://uitpaulineskeuken.nl/recept/meeneem-lunch-noedels-to-go', 'Meeneem lunch: noedels to go', 'Noedels to go als meeneemlunch'),
  ('https://uitpaulineskeuken.nl/recept/miso-ramen-met-gehaktballetjes', 'Miso ramen', 'Miso-ramen met gehakt en paksoi'),
  ('https://uitpaulineskeuken.nl/recept/miso-soep', 'Miso soep met shiitake', 'Misosoep met shiitake'),
  ('https://uitpaulineskeuken.nl/recept/noedelsoep-met-biefstuk', 'Noedelsoep met biefstuk en udon noodles', 'Udon-noedelsoep met biefstuk'),
  ('https://uitpaulineskeuken.nl/recept/pindasoep', 'Pindasoep met kokosmelk', 'Kokos-pindasoep met noedels'),
  ('https://uitpaulineskeuken.nl/recept/pittige-pompoensoep', 'Pittige pompoensoep', 'Pittige pompoensoep met kokos en gele curry'),
  ('https://uitpaulineskeuken.nl/recept/pompoen-wortelsoep', 'Pompoen wortelsoep', 'Soep van pompoen en wortel'),
  ('https://uitpaulineskeuken.nl/recept/preisoep-met-pesto-toast', 'Preisoep met pesto toast', 'Preisoep met toast met pesto'),
  ('https://uitpaulineskeuken.nl/recept/ribollita-soep-met-bonen', 'Ribollita soep met bonen en brood', 'Ribollita met bonen en brood'),
  ('https://uitpaulineskeuken.nl/recept/rode-currysoep', 'Rode currysoep', 'Rode currysoep met zoete aardappel'),
  ('https://uitpaulineskeuken.nl/recept/rode-linzensoep', 'Rode linzensoep', 'Soep van rode linzen'),
  ('https://uitpaulineskeuken.nl/recept/tomaten-cremesoep', 'Tomaten-crèmesoep', 'Tomatencrèmesoep met mascarpone'),
  ('https://uitpaulineskeuken.nl/recept/tomatensoep', 'Tomatensoep met balletjes', 'Tomatensoep met gehaktballetjes'),
  ('https://uitpaulineskeuken.nl/recept/turkse-linzensoep', 'Turkse linzensoep', 'Linzensoep op Turkse wijze'),
  ('https://uitpaulineskeuken.nl/recept/vegetarische-noedelsoep', 'Vegetarische noedelsoep', 'Vegetarische ramen-noedelsoep'),
  ('https://uitpaulineskeuken.nl/recept/vegetarische-soep', 'Vegetarische soep met orzo', 'Vegetarische orzosoep'),
  ('https://uitpaulineskeuken.nl/recept/venkelsoep', 'Venkelsoep met gerookte zalm', 'Soep van venkel met gerookte zalm'),
  ('https://uitpaulineskeuken.nl/recept/witlofsoep', 'Witlofsoep met ham en kaas', 'Witlofsoep met kaas en ham'),
  ('https://uitpaulineskeuken.nl/recept/witte-bonensoep', 'Witte bonensoep met kaascroutons', 'Wittebonensoep met kaascroutons'),
  ('https://uitpaulineskeuken.nl/recept/aubergine-salade', 'Aubergine salade', 'Auberginesalade met feta en platbrood'),
  ('https://uitpaulineskeuken.nl/recept/boerenkool-salade', 'Boerenkool salade met appel en kaas', 'Boerenkoolsalade met kaas en appel'),
  ('https://uitpaulineskeuken.nl/recept/caesar-pastasalade', 'Caesar pastasalade', 'Pastasalade caesar met kip'),
  ('https://uitpaulineskeuken.nl/recept/carpaccio-pastasalade', 'Carpaccio pastasalade', 'Pastasalade met carpaccio'),
  ('https://uitpaulineskeuken.nl/recept/chopped-salad', 'Chopped salad', 'Fijngesneden salade met kip en mango'),
  ('https://uitpaulineskeuken.nl/recept/couscoussalade-met-tonijn', 'Couscoussalade met tonijn', 'Tonijn-couscoussalade'),
  ('https://uitpaulineskeuken.nl/recept/crispy-rice-salad', 'Crispy rice salad', 'Salade met krokante rijst'),
  ('https://uitpaulineskeuken.nl/recept/green-goddess-salade', 'Green goddess salade', 'Green goddess-salade met groene groenten'),
  ('https://uitpaulineskeuken.nl/recept/griekse-rijstsalade', 'Griekse rijstsalade met feta en rozijnen', 'Griekse rijstsalade met rozijnen en feta'),
  ('https://uitpaulineskeuken.nl/recept/griekse-salade', 'Griekse salade', 'Griekse salade met feta en olijven'),
  ('https://uitpaulineskeuken.nl/recept/griekse-tortellini-salade', 'Griekse tortellini salade', 'Tortellinisalade op z''n Grieks'),
  ('https://uitpaulineskeuken.nl/recept/ham-prei-salade', 'Ham-prei salade', 'Salade met ham en prei'),
  ('https://uitpaulineskeuken.nl/recept/kisir', 'Kisir: Turkse bulgursalade', 'Kisir, bulgursalade uit Turkije'),
  ('https://uitpaulineskeuken.nl/recept/macaronisalade-met-feta', 'Macaronisalade met feta', 'Macaronisalade met feta en olijven'),
  ('https://uitpaulineskeuken.nl/recept/mango-kip-salade', 'Mango kip salade', 'Salade met gerookte kip en mango'),
  ('https://uitpaulineskeuken.nl/recept/mexicaanse-bonensalade', 'Mexicaanse bonensalade', 'Mexicaanse salade met drie soorten bonen'),
  ('https://uitpaulineskeuken.nl/recept/pastasalade-met-zalm', 'Pastasalade met zalm', 'Pastasalade met gerookte zalm en avocado'),
  ('https://uitpaulineskeuken.nl/recept/perzik-burrata-salade', 'Perzik burrata salade', 'Salade met perzik en burrata'),
  ('https://uitpaulineskeuken.nl/recept/quinoa-salade', 'Quinoa salade met halloumi', 'Quinoasalade met halloumi'),
  ('https://uitpaulineskeuken.nl/recept/roodlof-salade', 'Roodlof salade', 'Salade van roodlof met peer en brie'),
  ('https://uitpaulineskeuken.nl/recept/rundvleessalade', 'Rundvleessalade', 'Salade met rundvlees en aardappel'),
  ('https://uitpaulineskeuken.nl/recept/salade-lyonnaise', 'Salade Lyonnaise', 'Salade Lyonnaise met ei en spek'),
  ('https://uitpaulineskeuken.nl/recept/salade-met-aardbeien', 'Salade met aardbeien en geitenkaas', 'Salade met geitenkaas en aardbeien'),
  ('https://uitpaulineskeuken.nl/recept/salade-met-kip', 'Salade met kip', 'Salade met kip, spekjes en snijbonen'),
  ('https://uitpaulineskeuken.nl/recept/salade-met-misodressing', 'Salade met misodressing', 'Kipsalade met misodressing'),
  ('https://uitpaulineskeuken.nl/recept/salade-met-stracciatella', 'Salade met stracciatella', 'Salade met stracciatella en prosciutto'),
  ('https://uitpaulineskeuken.nl/recept/salade-met-venkel-en-sinaasappel', 'Salade met venkel en sinaasappel', 'Venkel-sinaasappelsalade'),
  ('https://uitpaulineskeuken.nl/recept/shoarma-salade', 'Shoarma salade', 'Salade met kipshoarma'),
  ('https://uitpaulineskeuken.nl/recept/simpele-couscous-salade', 'Simpele couscous salade met geitenkaas', 'Eenvoudige couscoussalade met geitenkaas'),
  ('https://uitpaulineskeuken.nl/recept/spaanse-salade', 'Spaanse salade', 'Spaanse salade met chorizo en reuzenbonen'),
  ('https://uitpaulineskeuken.nl/recept/vegetarische-pastasalade', 'Vegetarische pastasalade met Halloumi', 'Halloumi-pastasalade (vegetarisch)'),
  ('https://uitpaulineskeuken.nl/recept/zomersalade-met-aardbeien-en-burrata', 'Zomersalade met aardbeien en burrata', 'Zomerse salade met burrata en aardbeien'),
  ('https://uitpaulineskeuken.nl/recept/zomerse-pastasalade', 'Zomerse pastasalade', 'Zomerse pastasalade met groene asperges'),
  ('https://uitpaulineskeuken.nl/recept/aardappel-anders', 'Aardappel anders met chorizo', 'Aardappelschotel met chorizo uit de oven'),
  ('https://uitpaulineskeuken.nl/recept/aardappel-preischotel', 'Aardappel preischotel met romige kaassaus', 'Aardappel-preischotel in romige kaassaus'),
  ('https://uitpaulineskeuken.nl/recept/andijvie-ovenschotel', 'Andijvie ovenschotel', 'Andijvieschotel uit de oven met rookworst'),
  ('https://uitpaulineskeuken.nl/recept/bobotie', 'Bobotie met gehakt en sperzieboontjes', 'Bobotie met sperziebonen en gehakt'),
  ('https://uitpaulineskeuken.nl/recept/broccoli-uit-de-oven', 'Broccoli uit de oven met zalm', 'Zalm met broccoli uit de oven'),
  ('https://uitpaulineskeuken.nl/recept/enchiladas-met-gehakt', 'Enchilada''s met gehakt', 'Enchilada''s met gehakt en bonen'),
  ('https://uitpaulineskeuken.nl/recept/gehaktschotel', 'Italiaanse gehaktschotel', 'Italiaanse ovenschotel met gehakt en courgette'),
  ('https://uitpaulineskeuken.nl/recept/gevulde-aardappelen-uit-de-oven', 'Gevulde aardappelen uit de oven', 'Gevulde ovenaardappelen met broccoli en spek'),
  ('https://uitpaulineskeuken.nl/recept/gevulde-pompoen', 'Gevulde pompoen met orzo en kaas', 'Pompoen gevuld met orzo en kaas'),
  ('https://uitpaulineskeuken.nl/recept/gnocchi-uit-de-oven', 'Gnocchi uit de oven met paddenstoelen', 'Ovengnocchi met paddenstoelen'),
  ('https://uitpaulineskeuken.nl/recept/griekse-traybake', 'Griekse traybake met kipgyros', 'Kipgyros van de bakplaat op z''n Grieks'),
  ('https://uitpaulineskeuken.nl/recept/groene-lasagne', 'Groene lasagne met pesto', 'Groene pestolasagne'),
  ('https://uitpaulineskeuken.nl/recept/italiaanse-ovenschotel', 'Italiaanse ovenschotel met pasta', 'Italiaanse pastaschotel uit de oven'),
  ('https://uitpaulineskeuken.nl/recept/kabeljauw-uit-de-oven', 'Kabeljauw uit de oven', 'Ovengebakken kabeljauw'),
  ('https://uitpaulineskeuken.nl/recept/kip-in-de-hoed', 'Kip in de hoed', 'Kiptaart met een hoed van bladerdeeg'),
  ('https://uitpaulineskeuken.nl/recept/kipfilet-uit-de-oven', 'Kipfilet uit de oven met krieltjes', 'Kipfilet met krieltjes uit de oven'),
  ('https://uitpaulineskeuken.nl/recept/kippendijen-uit-de-oven', 'Kippendijen uit de oven', 'Ovengebakken kippendijen'),
  ('https://uitpaulineskeuken.nl/recept/lasagne-puttanesca', 'Lasagne puttanesca', 'Lasagne alla puttanesca met tonijn'),
  ('https://uitpaulineskeuken.nl/recept/mexicaanse-traybake', 'Mexicaanse traybake met spicy gehaktballetjes', 'Mexicaanse traybake met pittige gehaktballetjes'),
  ('https://uitpaulineskeuken.nl/recept/moussaka-met-zoete-aardappel', 'Moussaka met zoete aardappel', 'Moussaka van zoete aardappel'),
  ('https://uitpaulineskeuken.nl/recept/ovenschotel-met-broccoli-en-gehakt', 'Ovenschotel met broccoli en gehakt', 'Ovenschotel met gehakt en broccoli'),
  ('https://uitpaulineskeuken.nl/recept/ovenschotel-met-tonijn', 'Ovenschotel met tonijn en pasta', 'Tonijn-pastaschotel uit de oven'),
  ('https://uitpaulineskeuken.nl/recept/pasta-pesto-uit-de-oven', 'Pasta pesto uit de oven', 'Ovenpasta met pesto'),
  ('https://uitpaulineskeuken.nl/recept/pompoen-ovenschotel', 'Pompoen ovenschotel met aardappelpuree', 'Pompoenschotel uit de oven met aardappelpuree'),
  ('https://uitpaulineskeuken.nl/recept/prei-uit-de-oven', 'Prei uit de oven met kaassaus', 'Prei in kaassaus uit de oven'),
  ('https://uitpaulineskeuken.nl/recept/risotto-met-gehakt', 'Risotto met gehakt uit de oven', 'Ovenrisotto met gehakt'),
  ('https://uitpaulineskeuken.nl/recept/rode-kool-ovenschotel', 'Rode kool ovenschotel', 'Rodekoolschotel uit de oven met appel'),
  ('https://uitpaulineskeuken.nl/recept/spaanse-traybake', 'Spaanse traybake', 'Spaanse traybake met kip, chorizo en garnalen'),
  ('https://uitpaulineskeuken.nl/recept/spinazie-ovenschotel', 'Spinazie ovenschotel', 'Spinazieschotel uit de oven met spekjes'),
  ('https://uitpaulineskeuken.nl/recept/tartiflette-spek-kaas', 'Tartiflette met spek en kaas', 'Tartiflette met kaas en spek'),
  ('https://uitpaulineskeuken.nl/recept/thaise-traybake', 'Thaise traybake met groene curry kip', 'Thaise traybake met kip in groene curry'),
  ('https://uitpaulineskeuken.nl/recept/vegetarische-traybake', 'Vegetarische traybake met aubergine', 'Aubergine-traybake (vegetarisch)'),
  ('https://uitpaulineskeuken.nl/recept/vispastei', 'Vispastei', 'Vispastei met zalm, kabeljauw en garnalen'),
  ('https://uitpaulineskeuken.nl/recept/witlof-ovenschotel', 'Witlof ovenschotel met gehakt', 'Witlofschotel uit de oven met gehakt'),
  ('https://uitpaulineskeuken.nl/recept/witte-asperge-lasagne', 'Witte asperge lasagne', 'Lasagne met witte asperges'),
  ('https://uitpaulineskeuken.nl/recept/wraps-uit-de-oven-met-kip', 'Wraps uit de oven met kip', 'Kipwraps uit de oven'),
  ('https://miljuschka.nl/barbecue-spiesjes-van-gemarineerde-biefstuk-en-lente-ui-met-yoghurtdip/', 'Barbecue spiesjes van gemarineerde biefstuk en lente-ui, met yoghurtdip', 'Bbq-spiesjes met gemarineerde biefstuk, lente-ui en yoghurtdip'),
  ('https://miljuschka.nl/bbq-salade-met-entrecote-en-chimichurri-dressing/', 'BBQ-salade met entrecote en chimichurri dressing', 'Bbq-salade met entrecote en chimichurri'),
  ('https://miljuschka.nl/chili-cheeseburger-voor-op-de-bbq/', 'BBQ Chili Cheeseburger', 'Chili-cheeseburger van de bbq'),
  ('https://miljuschka.nl/coq-au-vin-stoofpot-van-kip-in-rode-wijn/', 'Coq au vin: stoofpot van kip in rode wijn', 'Coq au vin, kip gestoofd in rode wijn'),
  ('https://miljuschka.nl/eend-met-gebakken-zuurkool-eva-jinek/', 'Eend met gebakken zuurkool', 'Gebakken zuurkool met eend'),
  ('https://miljuschka.nl/gebakken-kabeljauw-met-tomatensalsa/', 'Gebakken kabeljauw met tomatensalsa', 'Kabeljauw uit de pan met tomatensalsa'),
  ('https://miljuschka.nl/gebakken-rijst-met-garnalen/', 'Gebakken rijst met garnalen', 'Garnalen met gebakken rijst'),
  ('https://miljuschka.nl/gebakken-zalm-met-bloemkool-knolselderijpuree-en-peterselie-pesto/', 'Gebakken zalm met bloemkool-knolselderijpuree en peterselie-pesto', 'Gebakken zalm met puree van bloemkool en knolselderij en peterseliepesto'),
  ('https://miljuschka.nl/gegrilde-dorade-in-bananenblad/', 'Gegrilde dorade in bananenblad', 'Dorade van de grill in bananenblad'),
  ('https://miljuschka.nl/geroosterde-rode-kool-met-dukkah/', 'Geroosterde rode kool met dukkah', 'Rode kool uit de oven met dukkah'),
  ('https://miljuschka.nl/geroosterde-tofu-met-noedelsalade/', 'Geroosterde tofu met noedelsalade', 'Noedelsalade met geroosterde tofu'),
  ('https://miljuschka.nl/gestoomde-broodjes-met-geroosterd-buikspek/', 'Gestoomde broodjes met geroosterd buikspek', 'Gestoomde broodjes gevuld met geroosterd buikspek'),
  ('https://miljuschka.nl/gezond-en-snel-mie-met-spitskool-broccoli-en-cashewnoten/', 'Mie met spitskool, broccoli en cashewnoten', 'Mie met broccoli, spitskool en cashewnoten'),
  ('https://miljuschka.nl/griekse-eenpans-orzo-met-kip-en-tomatensalade/', 'Griekse EEnpans orzo met kip en tomatensalade', 'Griekse orzo met kip uit één pan en tomatensalade'),
  ('https://miljuschka.nl/griekse-gehaktballetjes-met-fetakaascreme-en-orzosalade/', 'Griekse gehaktballetjes met fetakaascrème en salade', 'Griekse gehaktballetjes met salade en fetacrème'),
  ('https://miljuschka.nl/hele-geroosterde-knolselderij-uit-de-oven/', 'Hele geroosterde knolselderij uit de oven', 'Hele knolselderij, geroosterd in de oven'),
  ('https://miljuschka.nl/indiase-bbq-spies/', 'Indiase BBQ spies', 'Indiase kipspies van de bbq'),
  ('https://miljuschka.nl/karni-stoba-antilliaanse-stoofschotel-curacao/', 'Karni stobá', 'Karni stobá, Antilliaans stoofvlees'),
  ('https://miljuschka.nl/kipstoof-met-meiknol-en-orzo/', 'Kipstoof met meiknol en orzo', 'Kipstoof met orzo en meiknol'),
  ('https://miljuschka.nl/kruiden-tofuspiesjes-met-zomergroenten/', 'Kruiden-tofuspiesjes met zomergroenten', 'Tofuspiesjes met kruiden en zomergroenten'),
  ('https://miljuschka.nl/lamsrack-met-asperges-en-aardappels/', 'Lamsrack met asperges en aardappels', 'Lamsrack met aardappels en asperges'),
  ('https://miljuschka.nl/linzenstoof-met-aubergine/', 'Linzenstoof met aubergine', 'Stoof van linzen en aubergine'),
  ('https://miljuschka.nl/loetje-biefstuk-met-gebakken-uien-salade-john-van-den-heuvel/', 'Loetje style biefstuk - John van den Heuvel', 'Biefstuk van de ossenhaas met gebakken uien'),
  ('https://miljuschka.nl/makkelijke-vega-roerbak/', 'Makkelijke vega roerbak', 'Eenvoudige vegetarische roerbak met pompoen en krieltjes'),
  ('https://miljuschka.nl/pad-thai-met-kip-recept/', 'Pad Thai met kip recept', 'Pad thai met kip'),
  ('https://miljuschka.nl/papaja-mangosalade-met-geroosterde-zalm/', 'Papaja-mangosalade met geroosterde zalm', 'Salade van papaja en mango met geroosterde zalm'),
  ('https://miljuschka.nl/pittige-pompoenstoof-met-kaasknoedels/', 'Pittige pompoenstoof met kaasknoedels', 'Pompoenstoof met pit en kaasknoedels'),
  ('https://miljuschka.nl/pittige-roerbak-met-vega-gehakt-en-zwarte-bonen/', 'Pittige roerbak met (vega) gehakt en zwarte bonen', 'Pittige roerbak met zwarte bonen en (vega) gehakt'),
  ('https://miljuschka.nl/runderspiesjes-in-betelblad/', 'Runderspiesjes in betelblad', 'Spiesjes van rundergehakt in betelblad'),
  ('https://miljuschka.nl/snelle-roerbak-met-gehakt-peultjes-prei-en-champignons/', 'Snelle roerbak met gehakt, peultjes, prei en champignons', 'Snelle roerbak met gehakt, prei, peultjes en champignons'),
  ('https://miljuschka.nl/snelle-roerbak-met-groene-kool-en-biefstukpuntjes/', 'Groene kool roerbak met biefstukpuntjes', 'Roerbak van groene kool met biefstukpuntjes'),
  ('https://miljuschka.nl/surf-n-turf-stoofpotje/', 'Surf ‘n’ turf stoofpotje', 'Stoofpotje surf-and-turf'),
  ('https://miljuschka.nl/vegetarische-stoofschotel-met-parelgort-en-venkel/', 'Vegetarische stoofschotel van parelgort met venkel, bonen en trostomaten', 'Vegetarische stoof van parelgort, venkel, bonen en trostomaten'),
  ('https://deliciousmagazine.nl/recepten/minestrone-met-bonen-cavolo-nero-en-saucijzen/', 'Minestrone met bonen, cavolo nero en saucijzen', 'Minestrone met saucijs, bonen en cavolo nero')
) as n (url, oud, nieuw)
where r.url = n.url
  and r.bron_type = 'scraper'
  and coalesce(r.titel_nl, r.titel) = n.oud;
